In [2]:
!pip3 install numpy

In [11]:
import numpy as np

In [18]:
np.__version__

'1.19.2'

In [27]:
np.arange(0, 20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [29]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
np.arange(0, 20, 3)

array([ 0,  3,  6,  9, 12, 15, 18])